In [3]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn]))) ROC AUC

Saving kaggle.json to kaggle (1).json
User uploaded file "kaggle (1).json" with length 64 bytes


In [4]:
# Create a directory for the kaggle.json file
!mkdir ~/.kaggle

# Copy the kaggle.json file into the directory
# Assuming the uploaded file is named 'kaggle.json'
!cp kaggle.json ~/.kaggle/

# Set permissions for the kaggle.json file
!chmod 600 ~/.kaggle/kaggle.json

mkdir: cannot create directory ‘/root/.kaggle’: File exists


In [5]:
# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
mdsultanulislamovi_mental_disorders_dataset_path = kagglehub.dataset_download('mdsultanulislamovi/mental-disorders-dataset')

print('Data source import complete.')


100%|██████████| 2.17k/2.17k [00:00<00:00, 4.27MB/s]

Extracting files...
Data source import complete.


In [6]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [12]:
import numpy as np
import pandas as pd
data=pd.read_csv('/root/.cache/kagglehub/datasets/mdsultanulislamovi/mental-disorders-dataset/versions/1/mental_disorders_dataset.csv')

In [13]:
data.head()

Patient Number    Sadness    Euphoric  Exhausted Sleep dissorder Mood Swing  \
0     Patiant-01    Usually      Seldom  Sometimes       Sometimes        YES   
1     Patiant-02    Usually      Seldom    Usually       Sometimes         NO   
2     Patiant-03  Sometimes  Most-Often  Sometimes       Sometimes        YES   
3     Patiant-04    Usually      Seldom    Usually      Most-Often        YES   
4     Patiant-05    Usually     Usually  Sometimes       Sometimes         NO   

  Suicidal thoughts Anorxia Authority Respect Try-Explanation  \
0              YES       NO                NO             YES   
1               YES      NO                NO              NO   
2                NO      NO                NO             YES   
3               YES     YES                NO             YES   
4                NO      NO                NO              NO   

  Aggressive Response Ignore & Move-On Nervous Break-down Admit Mistakes  \
0                  NO               NO                YES            YES   
1                  NO               NO                 NO             NO   
2                 YES               NO                YES            YES   
3                  NO               NO                 NO             NO   
4                  NO               NO                YES            YES   

  Overthinking Sexual Activity Concentration  Optimisim Expert Diagnose  
0          YES       3 From 10     3 From 10  4 From 10  Bipolar Type-2  
1           NO       4 From 10     2 From 10  5 From 10      Depression  
2           NO       6 From 10     5 From 10  7 From 10  Bipolar Type-1  
3           NO       3 From 10     2 From 10  2 From 10  Bipolar Type-2  
4          YES       5 From 10     5 From 10  6 From 10          Normal

In [14]:
data.tail()

Patient Number     Sadness   Euphoric  Exhausted Sleep dissorder  \
115    Patiant-116  Most-Often     Seldom    Usually       Sometimes   
116    Patiant-117   Sometimes  Sometimes  Sometimes          Seldom   
117    Patiant-118     Usually  Sometimes    Usually       Sometimes   
118    Patiant-119     Usually  Sometimes     Seldom          Seldom   
119    Patiant-120   Sometimes    Usually     Seldom         Usually   

    Mood Swing Suicidal thoughts Anorxia Authority Respect Try-Explanation  \
115         NO               YES      NO                NO             YES   
116        YES                NO      NO                NO              NO   
117        YES                NO     YES               YES              NO   
118         NO               YES     YES                NO             YES   
119         NO                NO      NO               YES             YES   

    Aggressive Response Ignore & Move-On Nervous Break-down Admit Mistakes  \
115                  NO              YES                 NO             NO   
116                 YES               NO                 NO             NO   
117                  NO               NO                YES             NO   
118                 YES              YES                 NO            YES   
119                  NO              YES                YES             NO   

    Overthinking Sexual Activity Concentration  Optimisim Expert Diagnose  
115          YES       2 From 10     5 From 10  3 From 10      Depression  
116          YES       6 From 10     7 From 10  8 From 10  Bipolar Type-1  
117          YES       1 From 10     5 From 10  3 From 10  Bipolar Type-2  
118          YES       7 From 10     7 From 10  7 From 10      Depression  
119           NO       7 From 10     3 From 10  8 From 10          Normal

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   Patient Number       120 non-null    object
 1   Sadness              120 non-null    object
 2   Euphoric             120 non-null    object
 3   Exhausted            120 non-null    object
 4   Sleep dissorder      120 non-null    object
 5   Mood Swing           120 non-null    object
 6   Suicidal thoughts    120 non-null    object
 7   Anorxia              120 non-null    object
 8   Authority Respect    120 non-null    object
 9   Try-Explanation      120 non-null    object
 10  Aggressive Response  120 non-null    object
 11  Ignore & Move-On     120 non-null    object
 12  Nervous Break-down   120 non-null    object
 13  Admit Mistakes       120 non-null    object
 14  Overthinking         120 non-null    object
 15  Sexual Activity      120 non-null    object
 16  Concentr

In [16]:
data.describe()

Patient Number  Sadness Euphoric  Exhausted Sleep dissorder Mood Swing  \
count             120      120      120        120             120        120   
unique            120        4        4          4               4          2   
top        Patiant-01  Usually   Seldom  Sometimes       Sometimes         NO   
freq                1       42       46         38              44         63   

       Suicidal thoughts Anorxia Authority Respect Try-Explanation  \
count                120     120               120             120   
unique                 3       2                 2               2   
top                   NO      NO                NO              NO   
freq                  63      74                73              63   

       Aggressive Response Ignore & Move-On Nervous Break-down Admit Mistakes  \
count                  120              120                120            120   
unique                   2                2                  2              2   
top                     NO               NO                YES             NO   
freq                    62               70                 62             61   

       Overthinking Sexual Activity Concentration  Optimisim Expert Diagnose  
count           120             120           120        120             120  
unique            2               9             8          9               4  
top             YES       5 From 10     4 From 10  6 From 10  Bipolar Type-2  
freq             65              22            33         21              31

In [17]:
data.isnull().sum()

Patient Number         0
Sadness                0
Euphoric               0
Exhausted              0
Sleep dissorder        0
Mood Swing             0
Suicidal thoughts      0
Anorxia                0
Authority Respect      0
Try-Explanation        0
Aggressive Response    0
Ignore & Move-On       0
Nervous Break-down     0
Admit Mistakes         0
Overthinking           0
Sexual Activity        0
Concentration          0
Optimisim              0
Expert Diagnose        0
dtype: int64

In [18]:
data.isna().sum()

Patient Number         0
Sadness                0
Euphoric               0
Exhausted              0
Sleep dissorder        0
Mood Swing             0
Suicidal thoughts      0
Anorxia                0
Authority Respect      0
Try-Explanation        0
Aggressive Response    0
Ignore & Move-On       0
Nervous Break-down     0
Admit Mistakes         0
Overthinking           0
Sexual Activity        0
Concentration          0
Optimisim              0
Expert Diagnose        0
dtype: int64

In [20]:
for i in data.columns:
    print(f"\nValue counts for column:{i}")
    print(data[i].value_counts())


Value counts for column:Patient Number
Patient Number
Patiant-01     1
Patiant-02     1
Patiant-03     1
Patiant-04     1
Patiant-05     1
              ..
Patiant-116    1
Patiant-117    1
Patiant-118    1
Patiant-119    1
Patiant-120    1
Name: count, Length: 120, dtype: int64

Value counts for column:Sadness
Sadness
Usually       42
Sometimes     42
Most-Often    20
Seldom        16
Name: count, dtype: int64

Value counts for column:Euphoric
Euphoric
Seldom        46
Sometimes     45
Usually       20
Most-Often     9
Name: count, dtype: int64

Value counts for column:Exhausted
Exhausted
Sometimes     38
Usually       34
Most-Often    30
Seldom        18
Name: count, dtype: int64

Value counts for column:Sleep dissorder
Sleep dissorder
Sometimes     44
Usually       34
Most-Often    21
Seldom        21
Name: count, dtype: int64

Value counts for column:Mood Swing
Mood Swing
NO     63
YES    57
Name: count, dtype: int64

Value counts for column:Suicidal thoughts
Suicidal thoughts
NO 

In [19]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score,precision_score,recall_score,f1_score

In [21]:
X=data.drop(columns=["Patient Number","Expert Diagnose"])
y=data["Expert Diagnose"]
X_encoded=X.apply(LabelEncoder().fit_transform)
y_encoded=LabelEncoder().fit_transform(y)

In [22]:
X_train,X_test,y_train,y_test=train_test_split(X_encoded,y_encoded,test_size=0.2,random_state=42)

In [23]:
model=RandomForestClassifier(n_estimators=2500,random_state=42,class_weight='balanced')
model.fit(X_train,y_train)

RandomForestClassifier(class_weight='balanced', n_estimators=2500,
                       random_state=42)

In [24]:
y_pred=model.predict(X_test)

In [25]:
print("Accuracy:",accuracy_score(y_test,y_pred))
print("Recall:",recall_score(y_test,y_pred,average='weighted'))
print("Precision:",precision_score(y_test,y_pred,average='weighted'))
print("F1:",f1_score(y_test,y_pred,average='weighted'))
print("\nConfusion Matrix:\n",confusion_matrix(y_test,y_pred))
print("\nClassification Report:\n",classification_report(y_test,y_pred))

Accuracy: 0.8333333333333334
Recall: 0.8333333333333334
Precision: 0.8356481481481483
F1: 0.8322021116138764

Confusion Matrix:
 [[3 0 0 1]
 [0 5 0 0]
 [1 0 7 0]
 [0 0 2 5]]

Classification Report:
               precision    recall  f1-score   support

           0       0.75      0.75      0.75         4
           1       1.00      1.00      1.00         5
           2       0.78      0.88      0.82         8
           3       0.83      0.71      0.77         7

    accuracy                           0.83        24
   macro avg       0.84      0.83      0.84        24
weighted avg       0.84      0.83      0.83        24



In [27]:
from sklearn.model_selection import GridSearchCV
param_grid={
    'n_estimators':[1500,2000,2500],
    'max_depth':[None,10,20,30],
    'min_samples_split':[2,5,10],
    'min_samples_leaf':[1,2,4],
    'max_features':['sqrt','log2'],
    'bootstrap':[True,False]
}
rf=RandomForestClassifier(random_state=42,class_weight='balanced')
grid_search=GridSearchCV(estimator=rf,param_grid=param_grid,cv=5,scoring='f1_weighted',verbose=0,n_jobs=-1)
grid_search.fit(X_train,y_train)
print("Best Parameters are:",grid_search.best_params_)

Best Parameters are: {'bootstrap': True, 'max_depth': None, 'max_features': 'sqrt', 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 1500}


In [28]:
best_model=RandomForestClassifier(**grid_search.best_params_,random_state=42,class_weight='balanced')
best_model.fit(X_train,y_train)

RandomForestClassifier(class_weight='balanced', n_estimators=1500,
                       random_state=42)

In [29]:
y_pred_best=best_model.predict(X_test)
print("Tuned Accuracy:",accuracy_score(y_test,y_pred_best))
print("Tuned F1 Score:",f1_score(y_test,y_pred_best,average='weighted'))
print("Tuned Recall Score:",recall_score(y_test,y_pred_best,average='weighted'))
print("Tuned Precision Score:",precision_score(y_test,y_pred_best,average='weighted'))
print("\nTuned Confusion Matrix:\n",confusion_matrix(y_test,y_pred_best))
print("\nTuned Classification Report:\n",classification_report(y_test,y_pred_best))

Tuned Accuracy: 0.8333333333333334
Tuned F1 Score: 0.8322021116138764
Tuned Recall Score: 0.8333333333333334
Tuned Precision Score: 0.8356481481481483

Tuned Confusion Matrix:
 [[3 0 0 1]
 [0 5 0 0]
 [1 0 7 0]
 [0 0 2 5]]

Tuned Classification Report:
               precision    recall  f1-score   support

           0       0.75      0.75      0.75         4
           1       1.00      1.00      1.00         5
           2       0.78      0.88      0.82         8
           3       0.83      0.71      0.77         7

    accuracy                           0.83        24
   macro avg       0.84      0.83      0.84        24
weighted avg       0.84      0.83      0.83        24

